pipeline{
    agent any
    options {
        ansiColor('xterm')
        // timeout(time: 1, unit: 'HOURS')
        // disableConcurrentBuilds()
    }

    stages{
        stage('Init'){
            steps{
                sh'''
                    pwd
                    ls -ltr
                    terraform init
                '''
            }
        }
        stage('plan'){
            steps{
                sh'''
                    pwd
                    ls -ltr
                    cd Terraform
                    terraform plan
                '''
            }
        }
    }
    post{
        always{
            echo 'i will always run whether job is success or not'
        }
        success{
            echo 'i will run only when job is success'
        }
        failure{
            echo 'i will run when is failed '
        }
    }

}